export type InitialCompanyCatalogItem = {
  name: string;
  websiteUrl: string;
  domain: string;
  classification: string;
};

// Initial catalog imported from the attached table. Enrichment sections remain empty by design.
export const INITIAL_COMPANY_CATALOG: InitialCompanyCatalogItem[] = [
  { name: "Elm", websiteUrl: "https://www.elm.sa", domain: "الخدمات الرقمية", classification: "Enterprise Technology" },
  { name: "solutions by stc", websiteUrl: "https://solutions.com.sa", domain: "تقنية المعلومات", classification: "Enterprise Software" },
  { name: "STS", websiteUrl: "https://www.sts.com.sa", domain: "تقنية المعلومات", classification: "Enterprise Technology" },
  { name: "Ejari", websiteUrl: "https://ejari.sa", domain: "العقارات", classification: "PropTech" },
  { name: "Misk Skills", websiteUrl: "https://hub.misk.org.sa", domain: "التعليم", classification: "Learning Platform" },
  { name: "Noon Academy", websiteUrl: "https://www.noonacademy.com", domain: "التعليم", classification: "EdTech" },
  { name: "Abwaab", websiteUrl: "https://abwaab.com", domain: "التعليم", classification: "EdTech" },
  { name: "Synkers", websiteUrl: "https://synkers.com", domain: "التعليم", classification: "EdTech" },
  { name: "Raseel", websiteUrl: "https://raseel.com", domain: "التجارة الرقمية", classification: "Commerce Technology" },
  { name: "Retailo", websiteUrl: "https://retailo.co", domain: "تجارة B2B", classification: "B2B Commerce" },
  { name: "Sary", websiteUrl: "https://sary.com", domain: "تجارة B2B", classification: "B2B Commerce" },
  { name: "Nana", websiteUrl: "https://nana.sa", domain: "التجارة", classification: "Commerce Technology" },
  { name: "Shipa", websiteUrl: "https://shipa.com", domain: "اللوجستيات", classification: "Logistics Technology" },
  { name: "Flow Progressive Logistics", websiteUrl: "https://flowpl.com", domain: "اللوجستيات", classification: "Logistics Technology" },
  { name: "Logisti", websiteUrl: "https://logisti.sa", domain: "اللوجستيات", classification: "Logistics Technology" },
  { name: "Mrsool", websiteUrl: "https://mrsool.co", domain: "التوصيل", classification: "Delivery Technology" },
  { name: "HungerStation", websiteUrl: "https://hungerstation.com", domain: "التوصيل", classification: "Delivery Platform" },
  { name: "Jahez", websiteUrl: "https://jahez.net", domain: "التوصيل", classification: "Delivery Platform" },
  { name: "ToYou", websiteUrl: "https://toyou.io", domain: "الخدمات والتوصيل", classification: "Super App" },
  { name: "Shgardi", websiteUrl: "https://shgardi.app", domain: "التوصيل", classification: "Delivery Platform" },
  { name: "The Chefz", websiteUrl: "https://thechefz.co", domain: "الأغذية", classification: "FoodTech" },
  { name: "DailyMealz", websiteUrl: "https://dailymealz.com", domain: "الأغذية", classification: "Subscription FoodTech" },
  { name: "Calo", websiteUrl: "https://calo.app", domain: "الأغذية", classification: "Subscription Platform" },
  { name: "Morni", websiteUrl: "https://morni.com", domain: "السيارات", classification: "Mobility Technology" },
  { name: "Telgani", websiteUrl: "https://telgani.com", domain: "السيارات", classification: "Mobility Platform" },
  { name: "Syarah", websiteUrl: "https://syarah.com", domain: "السيارات", classification: "Automotive Technology" },
  { name: "Motory", websiteUrl: "https://motory.com", domain: "السيارات", classification: "Automotive Platform" },
  { name: "CarSwitch", websiteUrl: "https://carswitch.com", domain: "السيارات", classification: "Automotive Platform" },
  { name: "Eyewa", websiteUrl: "https://eyewa.com", domain: "التجارة الإلكترونية", classification: "E-commerce Technology" },
  { name: "Nice One", websiteUrl: "https://niceonesa.com", domain: "التجارة الإلكترونية", classification: "E-commerce" },
  { name: "Floward", websiteUrl: "https://floward.com", domain: "التجارة الإلكترونية", classification: "E-commerce" },
  { name: "ExpandCart", websiteUrl: "https://expandcart.com", domain: "التجارة الإلكترونية", classification: "E-commerce SaaS" },
  { name: "ShopGo", websiteUrl: "https://shopgo.me", domain: "التجارة الإلكترونية", classification: "E-commerce SaaS" },
  { name: "UTURN", websiteUrl: "https://uturn.com", domain: "المحتوى الرقمي", classification: "Digital Subscription" },
  { name: "Thmanyah", websiteUrl: "https://thmanyah.com", domain: "المحتوى الرقمي", classification: "Digital Subscription" },
  { name: "B8ak", websiteUrl: "https://b8ak.com", domain: "الخدمات الرقمية", classification: "Digital Platform" },
  { name: "Mrayti", websiteUrl: "https://mrayti.com", domain: "الخدمات", classification: "Digital Platform" },
  { name: "Barq", websiteUrl: "https://barq.com", domain: "الخدمات المالية", classification: "FinTech" },
  { name: "Tamam", websiteUrl: "https://tamam.life", domain: "التمويل", classification: "FinTech" },
  { name: "Tabby", websiteUrl: "https://tabby.ai", domain: "التقنية المالية", classification: "FinTech" },
  { name: "Tamara", websiteUrl: "https://tamara.co", domain: "التقنية المالية", classification: "FinTech" },
  { name: "STC Bank", websiteUrl: "https://stcbank.com.sa", domain: "الخدمات المالية", classification: "FinTech" },
  { name: "NymCard", websiteUrl: "https://nymcard.com", domain: "الخدمات المالية", classification: "FinTech API" },
  { name: "Raseed", websiteUrl: "https://raseed.com", domain: "التقنية المالية", classification: "FinTech" },
  { name: "Wafeq", websiteUrl: "https://wafeq.com", domain: "المحاسبة", classification: "Accounting SaaS" },
  { name: "Marn", websiteUrl: "https://marn.com", domain: "الموارد البشرية", classification: "HR Tech" },
  { name: "Merak Capital", websiteUrl: "https://merakcapital.com", domain: "التقنية", classification: "Technology" },
  { name: "IMPACT46", websiteUrl: "https://impact46.co", domain: "التقنية والاستثمار", classification: "Technology Ecosystem" },
  { name: "Cyberani", websiteUrl: "https://cyberani.com", domain: "الأمن السيبراني", classification: "Cybersecurity" },
  { name: "NourNet", websiteUrl: "https://nour.net.sa", domain: "السحابة", classification: "Cloud Technology" },
];
